name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call: # Usually called from deploy

defaults:
  run:
    shell: bash

permissions:
  checks: write  # for coverallsapp/github-action to create new checks
  contents: read  # for actions/checkout to fetch code

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        
      - name: Start services with Docker Compose
        run: |
          docker compose down
          docker compose build --build-arg NODE_ENV=development nodebb
          docker compose --profile redis up -d

      - name: Check if nyc is globally installed
        run: docker compose exec -T nodebb which nyc

      - name: Setup for Redis in container
        run: docker compose exec -T nodebb node app --setup="${SETUP}" --ci="${CI}"
        env:
          SETUP: >-
            {
              "url": "http://127.0.0.1:4567/forum",
              "secret": "abcdef",
              "admin:username": "admin",
              "admin:email": "test@example.org",
              "admin:password": "hAN3Eg8W",
              "admin:password:confirm": "hAN3Eg8W",
              "database": "redis",
              "redis:host": "redis",
              "redis:port": 6379,
              "redis:password": "",
              "redis:database": 0
            }
          CI: >-
            {
              "host": "redis",
              "database": 1,
              "port": 6379
            }

      - name: Run Node tests in container
        run: docker compose exec -T nodebb nyc --reporter=html --reporter=text-summary mocha

      - name: Stop Docker services
        run: docker compose down
        
 
